github:
  prebuilds:
    main: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: true

tasks:
  - name: Start Nix Shell
    init: nix-shell --run "purs --version"

vscode:
  extensions:
    - nwolverson.ide-purescript
    - emattiza.vscode-purty
    - nwolverson.language-purescript
