github:
  prebuilds:
    main: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: true

tasks:
  - name: Start Nix Shell
    init: nix-shell

vscode:
  extensions:
    - emattiza.ide-purescript
    - emattiza.vscode-purty
    - emattiza.language-purescript
